"""initial_schema

Revision ID: 47c304ccb844
Revises: 
Create Date: 2026-05-20 21:37:22.127032

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '47c304ccb844'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('news_articles',
    sa.Column('article_id', sa.String(length=36), nullable=False),
    sa.Column('source_url', sa.String(length=2048), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('fetched_at', sa.DateTime(), nullable=False),
    sa.Column('cached_until', sa.DateTime(), nullable=False),
    sa.Column('link_valid', sa.Boolean(), nullable=False),
    sa.Column('categories', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('article_id'),
    sa.UniqueConstraint('source_url')
    )
    op.create_index('idx_news_cached_until', 'news_articles', ['cached_until'], unique=False)
    op.create_index('idx_news_link_valid', 'news_articles', ['link_valid'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.String(length=12), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('provider', sa.String(length=20), nullable=False),
    sa.Column('provider_id', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=10), nullable=False),
    sa.Column('has_topics', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('provider', 'provider_id')
    )
    op.create_table('article_summaries',
    sa.Column('summary_id', sa.String(length=36), nullable=False),
    sa.Column('article_id', sa.String(length=36), nullable=False),
    sa.Column('summary_content', sa.Text(), nullable=False),
    sa.Column('word_count', sa.Integer(), nullable=True),
    sa.Column('llm_model', sa.String(length=50), nullable=True),
    sa.Column('generation_time_ms', sa.Integer(), nullable=True),
    sa.Column('cached_until', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['news_articles.article_id'], ),
    sa.PrimaryKeyConstraint('summary_id'),
    sa.UniqueConstraint('article_id')
    )
    op.create_index('idx_summary_cached_until', 'article_summaries', ['cached_until'], unique=False)
    op.create_table('audio_caches',
    sa.Column('audio_id', sa.String(length=36), nullable=False),
    sa.Column('article_id', sa.String(length=36), nullable=False),
    sa.Column('file_url', sa.String(length=1024), nullable=False),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('tts_engine', sa.String(length=50), nullable=True),
    sa.Column('file_size_bytes', sa.Integer(), nullable=True),
    sa.Column('cached_until', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['news_articles.article_id'], ),
    sa.PrimaryKeyConstraint('audio_id'),
    sa.UniqueConstraint('article_id')
    )
    op.create_index('idx_audio_article_id', 'audio_caches', ['article_id'], unique=False)
    op.create_index('idx_audio_cached_until', 'audio_caches', ['cached_until'], unique=False)
    op.create_table('collections',
    sa.Column('collection_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=12), nullable=False),
    sa.Column('article_id', sa.String(length=36), nullable=False),
    sa.Column('ai_summary', sa.Text(), nullable=True),
    sa.Column('keywords', sa.JSON(), nullable=True),
    sa.Column('vector_id', sa.String(length=100), nullable=True),
    sa.Column('collection_date', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['news_articles.article_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('collection_id'),
    sa.UniqueConstraint('user_id', 'article_id')
    )
    op.create_index('idx_collections_collection_date', 'collections', ['collection_date'], unique=False)
    op.create_index('idx_collections_user_id', 'collections', ['user_id'], unique=False)
    op.create_table('comments',
    sa.Column('comment_id', sa.String(length=36), nullable=False),
    sa.Column('article_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=12), nullable=False),
    sa.Column('parent_comment_id', sa.String(length=36), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('is_moderated', sa.Boolean(), nullable=False),
    sa.Column('moderation_score', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['news_articles.article_id'], ),
    sa.ForeignKeyConstraint(['parent_comment_id'], ['comments.comment_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('comment_id')
    )
    op.create_index('idx_comments_article_id', 'comments', ['article_id'], unique=False)
    op.create_index('idx_comments_parent_id', 'comments', ['parent_comment_id'], unique=False)
    op.create_index('idx_comments_user_id', 'comments', ['user_id'], unique=False)
    op.create_table('notifications',
    sa.Column('notification_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=12), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('channel', sa.String(length=10), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('notification_id')
    )
    op.create_index('idx_notifications_status', 'notifications', ['status'], unique=False)
    op.create_index('idx_notifications_user_id', 'notifications', ['user_id'], unique=False)
    op.create_table('preferences',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(length=12), nullable=False),
    sa.Column('tags', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('user_notification_prefs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(length=12), nullable=False),
    sa.Column('notify_email', sa.Boolean(), nullable=False),
    sa.Column('notify_line', sa.Boolean(), nullable=False),
    sa.Column('line_user_id', sa.String(length=100), nullable=True),
    sa.Column('email_address', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_notification_prefs')
    op.drop_table('preferences')
    op.drop_index('idx_notifications_user_id', table_name='notifications')
    op.drop_index('idx_notifications_status', table_name='notifications')
    op.drop_table('notifications')
    op.drop_index('idx_comments_user_id', table_name='comments')
    op.drop_index('idx_comments_parent_id', table_name='comments')
    op.drop_index('idx_comments_article_id', table_name='comments')
    op.drop_table('comments')
    op.drop_index('idx_collections_user_id', table_name='collections')
    op.drop_index('idx_collections_collection_date', table_name='collections')
    op.drop_table('collections')
    op.drop_index('idx_audio_cached_until', table_name='audio_caches')
    op.drop_index('idx_audio_article_id', table_name='audio_caches')
    op.drop_table('audio_caches')
    op.drop_index('idx_summary_cached_until', table_name='article_summaries')
    op.drop_table('article_summaries')
    op.drop_table('users')
    op.drop_index('idx_news_link_valid', table_name='news_articles')
    op.drop_index('idx_news_cached_until', table_name='news_articles')
    op.drop_table('news_articles')
    # ### end Alembic commands ###
